### ISSUE TITLE
easier install error

### ISSUE THREAD

**Issue by liangdp1984** [olapuentesantana/easier_manuscript#1]
I follow your install instruction and  also install dependency packages ‘progeny’, ‘viper’ and ‘dorothea’ ,  but i still can not install it properly!
library(devtools)
install_github("olapuentesantana/easier_manuscript")

* installing *source* package ‘easier’ ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘easier’ in namespaceExport(ns, exports):
 undefined exports: compute_CC_pairs, compute_CCpair_pval
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/ldp/miniconda2/envs/R4.0.3/lib/R/library/easier’
Error: Failed to install 'easier' from GitHub:

**Comment by olapuentesantana** [comment]
The error should have been fixed, you can try to install easier again.
Sorry for the inconvenience.

**Comment by liangdp1984** [comment]
> The error should have been fixed, you can try to install easier again.
> Sorry for the inconvenience.

thanks for your quick response! it works now!
