### ISSUE TITLE
missing internal Rdata files for easier

### ISSUE THREAD

**Issue by liangdp1984** [olapuentesantana/easier_manuscript#2]
i found some internal Rdata files were used in easier, for example: 

load("data/cor_genes_ICB_proxies.RData")
load("data/IPS_genes.RData")
load("data/list_top100pathways_responsive_genes.RData")
load("data/Ligand_Receptors_Rdata/intercell.network.CC.pairs.grouped.cancer.spec.RData")
load("data/resistance.program.RData")
load("data/grouping_lrpairs_features_info.RData")
load("data/TCGA_mean_sd.RData")

where can I  get access to these R.Data files???

LR_pairs_weights <- compute_LR_pairs(RNA.tpm=C4_tpm_exp_mat,
+                                     remove.genes.ICB_proxies=FALSE,
+                                     compute.cytokines.pairs=FALSE,
+                                     cancertype="pancan")
Error in compute_LR_pairs(RNA.tpm = C4_tpm_exp_mat, remove.genes.ICB_proxies = FALSE,  :
object 'intercell.network.cancer.spec' not found

**Comment by liangdp1984** [comment]
you created a data package 'Riaz_data'   via  usethis,  but  i can not load data using data("Riaz_data")

**Comment by liangdp1984** [comment]
you created a data package 'Riaz_data'   via  usethis,  but  i can not load data using data("Riaz_data")

**Comment by liangdp1984** [comment]
> Thanks for catching this!
> 
> Please follow the new instructions to install `easier`. The internal R.Data files should be now available at R/sysdata.rda.
> 
> As for the Riaz_data, I cannot make that data publicly available myself however I can point you to the corresponding study:
> Riaz N, Havel JJ, Makarov V, Desrichard A, Urba WJ, Sims JS, et al. . Tumor and microenvironment evolution during immunotherapy with nivolumab. Cell. (2017) 171:934–49.e16. 10.1016/j.cell.2017.09.028

I followed your new instructions to install easier, but i still failed to install the packages properly. It seems that something was wrong with sysdata.rda.  The error information is showen as below:

Enter one or more numbers, or an empty line to skip updates:3
✔  checking for file ‘/home/ldp/THCA/easier_manuscript-main/DESCRIPTION’ (413ms)
─  preparing ‘easier’:
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘easier_1.0.3.tar.gz’

Running /home/ldp/miniconda2/envs/R4.0.3/lib/R/bin/R CMD INSTALL \
  /tmp/RtmpiJ6z68/easier_1.0.3.tar.gz --install-tests
* installing to library ‘/home/ldp/miniconda2/envs/R4.0.3/lib/R/library’
* installing *source* package ‘easier’ ...
** using staged installation
** R
Warning: file ‘sysdata.rda’ has magic number 'versi'
  Use of save versions prior to 2 is deprecated
Error in load(srcFile, e) :
  bad restore file magic number (file may be corrupted) -- no data loaded
ERROR: unable to build sysdata DB for package ‘easier’
* removing ‘/home/ldp/miniconda2/envs/R4.0.3/lib/R/library/easier’
Error in (function (command = NULL, args = character(), error_on_status = TRUE,  :
  System command 'R' failed, exit status: 1, stdout & stderr were printed
Type .Last.error.trace to see where the error occured

**Comment by liangdp1984** [comment]
I followed your new instructions to install easier, but i still failed to install the packages properly. It seems that something was wrong with sysdata.rda.  The error information is showen as below:

Enter one or more numbers, or an empty line to skip updates:3
✔  checking for file ‘/home/ldp/THCA/easier_manuscript-main/DESCRIPTION’ (413ms)
─  preparing ‘easier’:
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘easier_1.0.3.tar.gz’

Running /home/ldp/miniconda2/envs/R4.0.3/lib/R/bin/R CMD INSTALL \
  /tmp/RtmpiJ6z68/easier_1.0.3.tar.gz --install-tests
* installing to library ‘/home/ldp/miniconda2/envs/R4.0.3/lib/R/library’
* installing *source* package ‘easier’ ...
** using staged installation
** R
Warning: file ‘sysdata.rda’ has magic number 'versi'
  Use of save versions prior to 2 is deprecated
Error in load(srcFile, e) :
  bad restore file magic number (file may be corrupted) -- no data loaded
ERROR: unable to build sysdata DB for package ‘easier’
* removing ‘/home/ldp/miniconda2/envs/R4.0.3/lib/R/library/easier’
Error in (function (command = NULL, args = character(), error_on_status = TRUE,  :
  System command 'R' failed, exit status: 1, stdout & stderr were printed
Type .Last.error.trace to see where the error occured

**Comment by liangdp1984** [comment]
I followed your new instructions to install easier, but i still failed to install the packages properly. It seems that something was wrong with sysdata.rda.  The error information is showen as below:

Enter one or more numbers, or an empty line to skip updates:3
✔  checking for file ‘/home/ldp/THCA/easier_manuscript-main/DESCRIPTION’ (413ms)
─  preparing ‘easier’:
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘easier_1.0.3.tar.gz’

Running /home/ldp/miniconda2/envs/R4.0.3/lib/R/bin/R CMD INSTALL \
  /tmp/RtmpiJ6z68/easier_1.0.3.tar.gz --install-tests
* installing to library ‘/home/ldp/miniconda2/envs/R4.0.3/lib/R/library’
* installing *source* package ‘easier’ ...
** using staged installation
** R
Warning: file ‘sysdata.rda’ has magic number 'versi'
  Use of save versions prior to 2 is deprecated
Error in load(srcFile, e) :
  bad restore file magic number (file may be corrupted) -- no data loaded
ERROR: unable to build sysdata DB for package ‘easier’
* removing ‘/home/ldp/miniconda2/envs/R4.0.3/lib/R/library/easier’
Error in (function (command = NULL, args = character(), error_on_status = TRUE,  :
  System command 'R' failed, exit status: 1, stdout & stderr were printed
Type .Last.error.trace to see where the error occured

**Comment by olapuentesantana** [comment]
Can you confirm that you are cloning the repository from github? I say this because if you download the repository directly as .zip file will probably not work.

**Comment by liangdp1984** [comment]
you are right!  I download the repository directly as .zip file.  At this time, i clone the repository via git,  it works well! Thanks for providing such a great tool for cancer research community!
