### ISSUE TITLE
predictions_immune_response errors

### ISSUE THREAD

**Issue by Jin0331** [olapuentesantana/easier_manuscript#5]
`trained_models[[any_cancer_type]] %>% names()`
[1] "pathways"    "immunecells" "tfs"         "lrpairs"    
[5] "ccpairs"   

in predict_immune_response **view name**s
```
  views <- c(Pathways.cor = 'gaussian',
             ImmuneCells = 'gaussian',
             TFs = 'gaussian',
             LRpairs.spec.pc = 'gaussian',
             CCpairsGroupedScores.spec.pc = 'gaussian')
```

The following error occurs because the "**view_name**" of trained_models and the "**view_name** "of predictions_immune_response do not match.

```
Error in array(STATS, dims[perm]) : 
  'data' must be of a vector type, was 'NULL'
```

Also,

Even if the above predict_immune_response "view names" are modified to those of trained_models and proceeded, in "**predict_with_multitaskelasticnet**", 

```
Error in matrix(as.matrix(Intercept), nrow = ncol(Slope), ncol = nrow(x.test[[1]])) :
  I get the same error as non-numeric matrix extent.
```

my R version
```
> version
               _                           
platform       aarch64-apple-darwin20      
arch           aarch64                     
os             darwin20                    
system         aarch64, darwin20           
status                                     
major          4                           
minor          1.0                         
year           2021                        
month          05                          
day            18                          
svn rev        80317                       
language       R                           
version.string R version 4.1.0 (2021-05-18)
nickname       Camp Pontanezen    
```

If possible, can you provide Docker images in which the easler works well?

**Comment by olapuentesantana** [comment]
Hello,

Thanks for pointing this error out.

As for the first comment:

Indeed, by default, the view names are not matching the names of the trained models and the first error pops up. 

Also, by default, the function predicts the immune response going through all combination of the views (while the trained models are only available for individual views) leading to a second error when using the `predict_with_multitaskelasticnet`function.

Both errors are now fixed and it should be possible to compute the predictions of immune response.

Please let me know if this solve the error.

Sorry for the inconvenience.

**Comment by Jin0331** [comment]
hello,
Using the code you modified, the immune response function was used without errors. thanks..!

However, in the case of Mean Square Error (mse), as far as I know, it is known as the loss value of the actual value and the predicted value. Can the loss value be interpreted as the patient's immune response value? If there is an interpretation method, I would appreciate it if you let me know.

I'm sorry for asking so many questions...! It's because I want to add what you've studied to my research.

**Comment by olapuentesantana** [comment]
Hi,

The function `predict_immune_response` returns an score for patients' immune response. This score is calculated based on the ensemble model, where higher values of easier score correspond to higher likelihood of immune response.

I hope this helps to answer your question.

**Comment by chayanit1234** [comment]
Hello, 

Could you please clarify after i ran the function predict_immune_response, it returned 1se.mse and min.mse. the value 1se.mse refers to patients' immune response?

Thank you

**Comment by chayanit1234** [comment]
and how we can get the overall view and overall tasks prediction?
in the function predict_immune_response, I only got the predict of single views

thank you

**Comment by olapuentesantana** [comment]
Hi,

`easier` is now available as a bioconductor package (https://www.bioconductor.org/packages/release/bioc/html/easier.html)

Now `predict_immune_response` returns predictions for each view using the trained model based on the lambda resulting from one standard error away (1se.mse) from the minimum square error (min.mse). We only kept the 1se.mse model predictions.

To obtain the overall view and the overall tasks, I recommend having a look at the vignette.

https://www.bioconductor.org/packages/release/bioc/vignettes/easier/inst/doc/easier_user_manual.html

Using `compute_scores_immune_response` function you get the value of each task, you can then compute the average to obtain the overall tasks prediction.

As for the overall view, it can be obtained through the function`retrieve_easier_score`. The easier_score column is the one corresponding to the overall views. You can just do:
`easier_derived_scores <- retrieve_easier_score(predictions_immune_response = predictions)`

Hopefully I answered your question.
